#!/usr/bin/env bash
# Bring up the OFF-cluster Kamailio + rtpengine edge for the k3d local
# call test. Joins the k3d Docker network, points Kamailio's dispatcher
# at the cluster's asterisk-edge NodePort, and self-signs a cert for the
# TLS/WSS listeners. NOT for production (there the edge runs on VMs).
#
# Prereq: the cluster side is deployed with values-local-edge.yaml
#         (see Stage 1 / helm/orbital/values-local-edge.yaml).
#
#   ./local/edge-up.sh
#
# Env overrides:
#   CLUSTER_NAME (orbital-dev), SIP_NODEPORT (31060),
#   EDGE_RTP_ADVERTISE_IP — set to a host-reachable IP when the softphone
#     runs on Windows/another host; leave empty for a softphone on the
#     k3d Docker network / WSL (rtpengine then advertises its own IP).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EDGE_DIR="${SCRIPT_DIR}/edge"
CLUSTER_NAME="${CLUSTER_NAME:-orbital-dev}"
export K3D_NETWORK="k3d-${CLUSTER_NAME}"
SIP_NODEPORT="${SIP_NODEPORT:-31060}"

command -v kubectl >/dev/null || { echo "ERROR: kubectl not found" >&2; exit 1; }
command -v openssl >/dev/null || { echo "ERROR: openssl not found" >&2; exit 1; }

# 1. Discover a k3d node IP (the Docker-network internal IP the edge dials).
NODE_IP="$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')"
[ -n "$NODE_IP" ] || { echo "ERROR: could not determine a k3d node IP" >&2; exit 1; }
echo "==> cluster Asterisk edge = ${NODE_IP}:${SIP_NODEPORT}"

# 2. dispatcher.list → the cluster's asterisk-edge NodePort.
cat > "${EDGE_DIR}/dispatcher.list" <<EOF
# GENERATED by local/edge-up.sh — Kamailio dispatches to the k3d cluster's
# asterisk-edge NodePort. Regenerated on every edge-up run.
1 sip:${NODE_IP}:${SIP_NODEPORT} 0 0 weight=100
EOF

# 3. Self-signed cert for the TLS (5061) + WSS (7443) listeners.
mkdir -p "${EDGE_DIR}/tls"
if [ ! -f "${EDGE_DIR}/tls/fullchain.pem" ]; then
    echo "==> generating self-signed edge cert"
    openssl req -x509 -newkey rsa:2048 -nodes -days 365 \
        -keyout "${EDGE_DIR}/tls/privkey.pem" \
        -out "${EDGE_DIR}/tls/fullchain.pem" \
        -subj "/CN=sip-edge.orbital.localhost" \
        -addext "subjectAltName=DNS:sip-edge.orbital.localhost,DNS:orbital.localhost,IP:127.0.0.1" \
        >/dev/null 2>&1
fi

# 4. rtpengine advertise interface. Default eth0 (its k3d IP) works when
#    the softphone shares the Docker network / WSL. For an off-host
#    softphone, EDGE_RTP_ADVERTISE_IP makes rtpengine bind all + advertise
#    that address (rtpengine NAT syntax: <bind>!<advertise>).
if [ -n "${EDGE_RTP_ADVERTISE_IP:-}" ]; then
    export RTPENGINE_INTERFACE="pub/0.0.0.0!${EDGE_RTP_ADVERTISE_IP}"
    echo "==> rtpengine advertises ${EDGE_RTP_ADVERTISE_IP}"
else
    export RTPENGINE_INTERFACE="eth0"
    echo "==> rtpengine advertises its k3d Docker IP (softphone must share that network/WSL)"
fi

# 5. Up (build kamailio image on first run).
echo "==> starting edge on ${K3D_NETWORK}"
docker compose -f "${EDGE_DIR}/docker-compose.yml" up -d --build

echo
echo "Edge up. Published on the host: SIP 5060(udp/tcp), TLS 5061, WSS 7443, JSON-RPC 8090, RTP 23000-23099."
echo "Dispatcher -> sip:${NODE_IP}:${SIP_NODEPORT}"
echo
echo "Next: run ./local/edge-register.sh to seed the rtpengine + Asterisk-backend rows"
echo "so the app's health cards + dispatcher reload work (Stage 3)."
echo "Tear down: ./local/edge-down.sh"
