<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api;

use App\Services\Telephony\AsteriskPeerResolver;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

/**
 * The current Kamailio dispatcher.list, for the SIP edge VMs.
 *
 * Asterisk pods move when Kubernetes replaces nodes, so the edges can't
 * keep a list fixed at first boot. Each edge polls this endpoint and
 * reloads its dispatcher when the list changes. Authenticated with the
 * same edge token the VMs already send to /api/tls/renewed.
 *
 * 503 when no Asterisk resolves: the edge keeps its last good list
 * rather than dispatching to nothing.
 */
class EdgeDispatcherController
{
    public function __invoke(Request $request, AsteriskPeerResolver $peers): Response
    {
        $expectedToken = (string) config('tls.webhook_token');
        $providedToken = $request->bearerToken() ?? '';

        if ($expectedToken === '' || ! hash_equals($expectedToken, $providedToken)) {
            return response('unauthorized', 401, ['Content-Type' => 'text/plain']);
        }

        $addresses = $peers->addresses();
        if ($addresses === []) {
            return response('no Asterisk found', 503, ['Content-Type' => 'text/plain']);
        }

        $setId = (int) config('telephony.kamailio.dispatcher_set_id', 1);
        $lines = ['# GENERATED by Orbital (/api/edge/dispatcher) from the ready Asterisk pods.'];
        foreach ($addresses as $ip) {
            $lines[] = sprintf('%d sip:%s:5060 0 0 weight=100', $setId, $ip);
        }

        return response(implode("\n", $lines)."\n", 200, ['Content-Type' => 'text/plain']);
    }
}
