<?php

declare(strict_types=1);

namespace App\Services\Telephony;

use App\Models\AsteriskBackend;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

/**
 * Writes the Kamailio dispatcher.list file from the
 * AsteriskBackend registry and triggers a dispatcher.reload on
 * every Kamailio node in the VRRP pair.
 *
 * File layout:
 *   # (generated preamble)
 *   1 sip:asterisk-1:5060 0 0 weight=100
 *   1 sip:asterisk-2:5060 0 0 weight=100
 *
 * Only `is_active` backends land in the file. Inactive rows stay
 * in the database (so history and preferences are kept) but
 * Kamailio doesn't even probe them.
 *
 * After a reload Kamailio resets every backend to `AP` (active
 * + probing), which wipes runtime drain state. The caller is
 * responsible for re-applying any operator-set drain state on
 * backends that were already draining — that happens in the
 * Filament resource's save hook via AsteriskDrainService.
 */
class AsteriskDispatcherWriter
{
    public function __construct(
        protected KamailioService $kamailio,
        protected string $path = '/var/www/html/docker/kamailio/dispatcher.list',
    ) {}

    /**
     * Regenerate the dispatcher file and reload Kamailio.
     *
     * @return array{wrote: bool, reloaded: array<string, bool>}
     */
    public function regenerate(): array
    {
        $contents = $this->render();
        $wrote = @file_put_contents($this->path, $contents) !== false;

        if (! $wrote) {
            Log::error('asterisk-dispatcher: failed to write dispatcher.list', [
                'path' => $this->path,
            ]);

            return ['wrote' => false, 'reloaded' => []];
        }

        $reloaded = $this->reloadAll();

        Log::info('asterisk-dispatcher: regenerated + reloaded', [
            'path' => $this->path,
            'reloaded' => $reloaded,
        ]);

        return ['wrote' => $wrote, 'reloaded' => $reloaded];
    }

    protected function render(): string
    {
        $lines = [
            '# Dispatcher set 1 — Asterisk backends.',
            '# GENERATED by AsteriskDispatcherWriter — edits to this file',
            '# will be overwritten on the next save in the admin UI.',
            '#',
            '# Format: setid destination flags priority attrs',
            '#   setid=1 → the SIP-trunk pool Kamailio dispatches to',
            '#   flags=0 → no special flags (drain state applied at runtime)',
            '#   priority=0 → equal (ds_select_dst algo 0 hashes by Call-ID)',
            '#   attrs=weight=100 → equal weighting',
            '',
        ];

        $backends = AsteriskBackend::query()
            ->active()
            ->orderBy('sort_order')
            ->orderBy('hostname')
            ->get();

        if ($backends->isEmpty()) {
            // Leave a clear breadcrumb rather than an empty set — an
            // empty dispatcher.list would make every inbound call
            // return 503 "Service Unavailable" from Kamailio. The
            // sentinel entry below is deliberately unreachable so
            // probing drops it to inactive immediately, but Kamailio
            // itself still boots.
            $lines[] = '# WARNING: no active AsteriskBackend rows configured.';
            $lines[] = '# Add at least one backend in the admin UI.';
            $lines[] = '1 sip:127.0.0.1:65534 0 0 weight=100';
        } else {
            foreach ($backends as $b) {
                $lines[] = sprintf(
                    '1 %s 0 0 weight=100',
                    $b->sipUri(),
                );
            }
        }

        return implode("\n", $lines)."\n";
    }

    /**
     * Call dispatcher.reload on every Kamailio node. Fan-out is
     * already built into KamailioService — we ask it for the URL
     * list via the setBackendState shape so reload hits every
     * node the drain path would hit.
     *
     * @return array<string, bool>
     */
    protected function reloadAll(): array
    {
        $urls = (array) config('telephony.kamailio.jsonrpc_urls', []);
        if (empty($urls)) {
            $single = (string) config('telephony.kamailio.jsonrpc_url');
            $urls = $single === '' ? [] : [$single];
        }

        $results = [];
        foreach ($urls as $url) {
            try {
                $resp = Http::timeout(3)
                    ->withHeaders(['Content-Type' => 'application/json'])
                    ->post($url, [
                        'jsonrpc' => '2.0',
                        'method' => 'dispatcher.reload',
                        'id' => 1,
                    ]);
                $results[$url] = $resp->successful()
                    && ! isset($resp->json()['error']);
            } catch (\Throwable $e) {
                Log::warning('asterisk-dispatcher: reload failed', [
                    'url' => $url,
                    'error' => $e->getMessage(),
                ]);
                $results[$url] = false;
            }
        }

        return $results;
    }
}
