<?php

return [

    /*
    |--------------------------------------------------------------------------
    | TLS Certificate Management
    |--------------------------------------------------------------------------
    |
    | Centralized TLS config for the platform. When `enabled` is true,
    | the admin UI surfaces the TLS Certificates page under Administration
    | and the health probe treats cert expiry as a monitored condition.
    |
    | Certs are issued by acme.sh via Let's Encrypt DNS-01 validation
    | and written to a shared Docker volume that every consuming service
    | mounts read-only. The CertificateService reads the PEM files from
    | `cert_path` / `key_path` and parses them with openssl_x509_parse
    | for the dashboard — no database model, just filesystem reads.
    |
    | In Kubernetes, cert-manager replaces acme.sh and writes the same
    | PEM files to the same mount path via a Secret volume. The app
    | code is environment-agnostic.
    |
    */

    'enabled' => (bool) env('ACME_ENABLED', false),

    // The base domain to issue a wildcard cert for.
    // acme.sh issues *.{domain} + {domain} via DNS-01.
    'domain' => env('ACME_DOMAIN', ''),

    // acme.sh DNS plugin name — matches the dnsapi wiki page:
    // https://github.com/acmesh-official/acme.sh/wiki/dnsapi
    // Examples: dns_cf (Cloudflare), dns_aws (Route53), dns_gd (GoDaddy)
    'dns_provider' => env('ACME_DNS_PROVIDER', 'dns_cf'),

    // Filesystem paths where the managed cert lives. These match
    // what acme.sh writes to the tls-certs shared volume via
    // --install-cert. Every consuming service mounts the same
    // volume at /etc/tls/ (or a service-specific path that
    // symlinks to it).
    'cert_path' => env('TLS_CERT_PATH', '/etc/tls/fullchain.pem'),
    'key_path' => env('TLS_KEY_PATH', '/etc/tls/privkey.pem'),

    // Shared secret for the deploy-hook webhook. acme.sh's
    // deploy-hook.sh POSTs to /api/tls/renewed with this token
    // after each successful renewal so Laravel can dispatch
    // service-reload jobs. Generated by the SsoSecretsBootstrapper
    // or manually via `openssl rand -hex 24`.
    'webhook_token' => env('ACME_WEBHOOK_TOKEN', ''),

];
