---
- name: restart rtpengine
  ansible.builtin.systemd:
    name: ngcp-rtpengine-daemon
    state: restarted

- name: restart rtpengine-recording
  ansible.builtin.systemd:
    name: ngcp-rtpengine-recording-daemon
    state: restarted
