{{--
    Per-client dialplan file. One copy of this file per client lives
    at /etc/asterisk/generated/clients/{team_id}-dialplan.conf and is
    #include'd from generated/dialplan_index.conf.

    The whole point of splitting client dialplans into separate files
    is reload scoping: when a client's RoutingRule changes, the
    generator only rewrites this one file (plus the from-trunk
    dispatcher) and triggers a `dialplan reload`, never a full
    Asterisk reload. At 1000 clients that's the difference between
    rewriting one ~500-byte file and rewriting a single multi-MB blob
    on every operator edit.

    Variables in scope:
        $team       — App\Models\Team
        $extensions — collection of active extensions for this client
        $queues     — collection of active queues for this client
        $context    — the canonical context name (e.g. "tenant_42")
--}}
;===============================================================================
; client {{ $team->id }} ({{ $team->name }}) dialplan
; Generated: {{ now()->toIso8601String() }}
; DO NOT EDIT — regenerated by App\Services\Telephony\AsteriskConfigService
;===============================================================================

[{{ $context }}]

; ── Extensions ──
@foreach($extensions->where('type', 'ai_agent') as $ext)
exten => {{ $ext->number }},1,NoOp(AI Agent: {{ $ext->label ?? $ext->number }})
 same => n,Dial(PJSIP/{{ $ext->number }}@livekit,120,tTkK)
 same => n,Hangup()

@endforeach
@foreach($extensions->whereNotIn('type', ['ai_agent']) as $ext)
exten => {{ $ext->number }},1,NoOp(Dialing {{ $ext->label ?? 'extension' }} {{ $ext->number }})
@include('asterisk.partials.mix-monitor', ['ext' => $ext])
 same => n,Dial(PJSIP/{{ $ext->number }},18,tTkK)
 same => n,GotoIf($["${DIALSTATUS}" = "BUSY"]?busy:unavail)
 same => n(busy),VoiceMail({{ $ext->number }}@@default,b)
 same => n,Hangup()
 same => n(unavail),VoiceMail({{ $ext->number }}@@default,u)
 same => n,Hangup()

@endforeach

; ── Call Queues ──
@foreach($queues as $queue)
exten => queue-{{ $queue->id }},1,NoOp(Queue: {{ $queue->name }} -> {{ $queue->asteriskName() }})
 same => n,Answer()
 same => n,Queue({{ $queue->asteriskName() }},tTkK,,,{{ $queue->timeout }})
@if($queue->overflowAgent)
 same => n,NoOp(Overflow to AI agent: {{ $queue->overflowAgent->name }})
 same => n,Dial(PJSIP/{{ $queue->overflowAgent->extensions->first()?->number ?? '0' }}@livekit,120,tTkK)
@endif
 same => n,Hangup()

@endforeach
