;===============================================================================
; extensions_generated.conf — Auto-generated by Orbital
; DO NOT EDIT — changes will be overwritten
; Generated: {{ now()->toIso8601String() }}
;
; [general] lives in the baked /etc/asterisk/extensions.conf which
; #tryinclude's this file. We emit [globals] and contexts below; the
; two files merge cleanly rather than double-defining.
;===============================================================================

[globals]
OPERATOR = 1001

;───────────────────────────────────────────────────────────────────────────────
; INTERNAL CONTEXT
;───────────────────────────────────────────────────────────────────────────────
[internal]

; ── Echo test (*43) ──
exten => *43,1,NoOp(Echo test)
 same => n,Answer()
 same => n,Playback(demo-echotest)
 same => n,Echo()
 same => n,Playback(demo-echodone)
 same => n,Hangup()

; ── Speaking clock (*60) ──
exten => *60,1,NoOp(Speaking clock)
 same => n,Answer()
 same => n,SayUnixTime(,,IMp)
 same => n,Hangup()

@if($internalDidSimulation)
; ── Internal DID simulation ──
; When an operator dials a client's external DID from a softphone
; (e.g. 15550000001), bounce the call into [from-trunk] so it takes
; the exact same routing path a real inbound SIP trunk call would.
; Guarded by config('telephony.asterisk.internal_did_simulation'),
; off by default — disable in production so operators can't
; self-originate "inbound" calls.
;
; Matches any 11-digit number starting with 1 (US E.164 shape).
; Deliberately looser than strict NANP (_1NXXNXXXXXX) because the
; demo template DIDs like 15550000001 have `000` as the exchange,
; which fails real NANP validation. Template testing should still
; route cleanly even with invalid-in-the-wild fake numbers.
exten => _1XXXXXXXXXX,1,NoOp(Internal DID simulation: ${EXTEN})
 same => n,Goto(from-trunk,${EXTEN},1)
@endif

; ── AI Agent Extensions (via LiveKit) ──
@foreach($extensions->where('type', 'ai_agent') as $ext)
exten => {{ $ext->number }},1,NoOp(AI Agent: {{ $ext->label ?? $ext->number }})
 same => n,Dial(PJSIP/{{ $ext->number }}@livekit,120,tTkK)
 same => n,Hangup()
@endforeach

; ── Internal Extensions ──
@foreach($extensions->whereNotIn('type', ['ai_agent']) as $ext)
exten => {{ $ext->number }},1,NoOp(Dialing {{ $ext->label ?? 'extension' }} {{ $ext->number }})
@include('asterisk.partials.mix-monitor', ['ext' => $ext])
 same => n,Dial(PJSIP/{{ $ext->number }},18,tTkK)
 same => n,GotoIf($["${DIALSTATUS}" = "BUSY"]?busy:unavail)
 same => n(busy),VoiceMail({{ $ext->number }}@@default,b)
 same => n,Hangup()
 same => n(unavail),VoiceMail({{ $ext->number }}@@default,u)
 same => n,Hangup()
@endforeach

; ── Call Queues ──
@foreach($queues as $queue)
exten => queue-{{ $queue->id }},1,NoOp(Queue: {{ $queue->name }} -> {{ $queue->asteriskName() }})
 same => n,Answer()
 same => n,Queue({{ $queue->asteriskName() }},tTkK,,,{{ $queue->agentGroup?->strategyTemplate?->timeout ?? 30 }})
@if($queue->overflowAgent)
 same => n,NoOp(Overflow to AI agent: {{ $queue->overflowAgent->name }})
 same => n,Dial(PJSIP/{{ $queue->overflowAgent->extensions->first()?->number ?? '0' }}@livekit,120,tTkK)
@endif
 same => n,Hangup()
@endforeach

;───────────────────────────────────────────────────────────────────────────────
; NOTE: [from-trunk] and [from-livekit] are intentionally NOT defined here.
; They live in the dedicated from-trunk.conf (generateFromTrunkDispatcher),
; which dialplan_index.conf also #includes. Defining them here too would
; double-register their `_X.` extensions ("already in use") and, worse,
; route inbound calls to `internal` instead of the correct per-client
; context. This file owns [globals] + [internal] only.
;───────────────────────────────────────────────────────────────────────────────
