;===============================================================================
; pjsip_generated.conf — Auto-generated by Orbital
; DO NOT EDIT — changes will be overwritten
; Generated: {{ now()->toIso8601String() }}
;
; Transports (UDP 5060, TCP 5060, TLS 5061, WSS 8089) are declared in
; the baked /etc/asterisk/pjsip.conf and are NOT emitted here. This
; file holds tenant-owned content only: endpoint templates, extensions,
; and SIP trunks. #tryinclude'd from pjsip.conf.
;===============================================================================

;───────────────────────────────────────────────────────────────────────────────
; ENDPOINT TEMPLATES
;───────────────────────────────────────────────────────────────────────────────

[endpoint-internal](!)
type = endpoint
context = internal
disallow = all
allow = ulaw
allow = alaw
allow = g722
allow = opus
direct_media = no
trust_id_inbound = yes
device_state_busy_at = 1
dtmf_mode = rfc4733
rtp_symmetric = yes
force_rport = yes
rewrite_contact = yes

[auth-internal](!)
type = auth
auth_type = userpass

[aor-single](!)
type = aor
max_contacts = 1
qualify_frequency = 30
remove_existing = yes

[endpoint-webrtc](!)
type = endpoint
context = internal
disallow = all
allow = opus
allow = ulaw
transport = transport-wss
webrtc = yes
dtls_auto_generate_cert = yes
media_encryption = dtls
dtls_verify = fingerprint
dtls_setup = actpass
ice_support = yes
media_use_received_transport = yes
rtcp_mux = yes
direct_media = no
trust_id_inbound = yes
device_state_busy_at = 1
dtmf_mode = rfc4733
rtp_symmetric = yes
force_rport = yes
rewrite_contact = yes

;───────────────────────────────────────────────────────────────────────────────
; EXTENSIONS
;───────────────────────────────────────────────────────────────────────────────
@foreach($extensions as $ext)

; --- {{ $ext->label ?? $ext->number }} ({{ $ext->type }}) ---
@if($ext->type === 'webrtc')
[{{ $ext->number }}](endpoint-webrtc)
@else
[{{ $ext->number }}](endpoint-internal)
@endif
auth = {{ $ext->number }}
aors = {{ $ext->number }}
callerid = "{{ $ext->label ?? 'Ext '.$ext->number }}" <{{ $ext->number }}>

[{{ $ext->number }}](auth-internal)
username = {{ $ext->sip_username ?? $ext->number }}
password = {{ $ext->sip_password ?? 'changeme' }}

@if($ext->type === 'webrtc')
[{{ $ext->number }}]
type = aor
max_contacts = 5
remove_existing = no
qualify_frequency = 30
@else
[{{ $ext->number }}](aor-single)
@endif
@endforeach

;───────────────────────────────────────────────────────────────────────────────
; SIP TRUNKS
;───────────────────────────────────────────────────────────────────────────────
@foreach($trunks as $trunk)

; --- Trunk: {{ $trunk->name }} ({{ $trunk->provider ?? 'custom' }}) ---
[trunk-{{ $trunk->id }}]
type = endpoint
context = {{ $trunk->inbound_context }}
transport = transport-{{ $trunk->transport }}
disallow = all
@foreach($trunk->codecs ?? ['ulaw', 'alaw'] as $codec)
allow = {{ $codec }}
@endforeach
direct_media = no
dtmf_mode = rfc4733
rtp_symmetric = yes
force_rport = yes
rewrite_contact = yes
aors = trunk-{{ $trunk->id }}
@if($trunk->username)
outbound_auth = trunk-{{ $trunk->id }}-auth
@endif

@if($trunk->username)
[trunk-{{ $trunk->id }}-auth]
type = auth
auth_type = userpass
username = {{ $trunk->username }}
password = {{ $trunk->password }}
@endif

[trunk-{{ $trunk->id }}]
type = aor
contact = sip:{{ $trunk->host }}:{{ $trunk->port }}
qualify_frequency = 30

[trunk-{{ $trunk->id }}-identify]
type = identify
endpoint = trunk-{{ $trunk->id }}
match = {{ $trunk->host }}
@endforeach
