;===============================================================================
; queues_generated.conf — Auto-generated by Orbital
; DO NOT EDIT — changes will be overwritten
; Generated: {{ now()->toIso8601String() }}
;
; [general] lives in the baked /etc/asterisk/queues.conf which
; #tryinclude's this file. This file holds queue definitions only.
;===============================================================================

@foreach($queues as $queue)
[{{ $queue->name }}]
strategy = {{ $queue->strategy }}
timeout = {{ $queue->timeout }}
retry = {{ $queue->retry }}
wrapuptime = {{ $queue->wrapup_time }}
maxlen = {{ $queue->max_callers }}
musicclass = {{ $queue->music_on_hold }}
joinempty = {{ $queue->join_empty ? 'yes' : 'no' }}
leavewhenempty = {{ $queue->leave_when_empty ? 'yes' : 'no' }}
@foreach($queue->members as $member)
member => PJSIP/{{ $member->extension->number }},{{ $member->penalty }},{{ $member->extension->label ?? $member->extension->number }},{{ $member->extension->number }}
@endforeach

@endforeach
