{{--
    voicemail.conf — generated from clients with a voicemail
    routing rule. Every client gets one mailbox whose number equals
    the client's account_number. New-message emails go to the
    client's primary contact with the audio attached.

    Variables in scope:
        $mailboxes — list of arrays {mailbox, password, fullname,
                     email} for clients that have at least one
                     RoutingRule with destination_type='voicemail'.
--}}
;===============================================================================
; voicemail.conf
; Generated: {{ now()->toIso8601String() }}
; DO NOT EDIT — regenerated by App\Services\Telephony\AsteriskConfigService
;===============================================================================

[general]
; Record WAV + GSM. WAV goes into the email attachment because most
; MUAs play it natively; GSM stays on disk as the compact copy.
format=wav49|gsm|wav
attach=yes
skipms=3000
silencethreshold=128
maxlogins=3
moveheard=yes
; maxsilence must be LESS than minsecs or Asterisk drops short
; messages as empty (the silence timer trips before the min-duration
; threshold). We want 3-second minimum message and 2-second silence
; cutoff so callers who pause briefly still have their message saved.
minsecs=3
maxsilence=2
maxsecs=120
maxmsg=200
review=no
operator=no
envelope=no
nextaftercmd=yes
forcename=no
forcegreetings=no

; externnotify fires after a new voicemail lands. The script POSTs
; to Laravel's /api/voicemail/received webhook, which queues the
; transcription job and the rich email Mailable. Keep Asterisk's
; own email= path UNSET on mailboxes so we don't double-deliver.
externnotify=/usr/local/bin/notify-voicemail.sh

[zonemessages]
eastern=America/New_York|'vm-received' Q 'digits/at' IMp
central=America/Chicago|'vm-received' Q 'digits/at' IMp
mountain=America/Denver|'vm-received' Q 'digits/at' IMp
pacific=America/Los_Angeles|'vm-received' Q 'digits/at' IMp

[default]
; Mailboxes: one per client with a voicemail routing rule.
; Format: mailbox => password,fullname,email,pager,options
; Email field is INTENTIONALLY blank — Laravel's transcription +
; email pipeline (triggered by externnotify above) owns delivery.
; Setting email here would cause Asterisk to double-send.
@foreach($mailboxes as $mb)
{{ $mb['mailbox'] }} => {{ $mb['password'] }},{{ $mb['fullname'] }},,,tz=eastern
@endforeach
@if(count($mailboxes) === 0)
; No clients have a voicemail routing rule configured. Add one via
; the admin UI and regenerate configs (orbital:generate-config).
@endif
